version: '3.9'

services:
  email_tracker:
    container_name: email_tracker
    build: .
    command: python manage.py runserver 0.0.0.0:4040
    volumes:
      - email_tracker_open_media_volume:/email_tracker/open_media
      - email_tracker_static_volume:/email_tracker/static
      - .:/email_tracker
    depends_on:
      - email_tracker_db
    ports:
      - "4040:4040"
      - "4141:4141" # Debugger
    env_file: 
      - .env.dev
    networks:
      - email_tracker_network

  email_tracker_db:
    container_name: email_tracker_db
    image: postgres:12.2
    ports:
      - "5433:5432"
    env_file:
      - .env.dev
    networks:
      - email_tracker_network

  email_tracker_nginx:
    container_name: email_tracker_nginx
    restart: always
    image: nginx:stable
    ports:
      - "5050:5050"
    networks:
      - email_tracker_network
    depends_on:
      - email_tracker
    volumes:
      - email_tracker_open_media_volume:/email_tracker/open_media
      - email_tracker_static_volume:/email_tracker/static
      - ./nginx_dev/nginx.conf:/etc/nginx/conf.d/default.conf


volumes:
  email_tracker_open_media_volume:
  email_tracker_static_volume:

networks:
  email_tracker_network: