version: '3.9'

services:
  email_tracker_prod:
    container_name: email_tracker_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: daphne -b 0.0.0.0 -p 4040 email_tracker.asgi:application
    volumes:
      - email_tracker_prod_open_media_volume:/email_tracker/open_media
      - email_tracker_prod_static_volume:/email_tracker/static
      - email_tracker_prod_loggers_volume:/email_tracker/loggers
    depends_on:
      - email_tracker_prod_db
    ports:
      - "4040:4040"
    env_file: 
      - .env.prod
    networks:
      - email_tracker_prod_network

  email_tracker_prod_db:
    container_name: email_tracker_prod_db
    image: postgres:12.2
    ports:
      - "5433:5432"
    env_file:
      - .env.prod
    networks:
      - email_tracker_prod_network

  email_tracker_prod_nginx:
    container_name: email_tracker_prod_nginx
    restart: always
    image: nginx:stable
    ports:
      - "5050:5050"
    networks:
      - email_tracker_prod_network
    depends_on:
      - email_tracker_prod
    volumes:
      - email_tracker_prod_open_media_volume:/email_tracker/open_media
      - email_tracker_prod_static_volume:/email_tracker/static
      - email_tracker_prod_loggers_volume:/email_tracker/loggers
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf


volumes:
  email_tracker_prod_open_media_volume:
  email_tracker_prod_static_volume:
  email_tracker_prod_loggers_volume:

networks:
  email_tracker_prod_network: